// Single source of truth for the site's canonical origin. Used by the sitemap,
// robots file, and page metadata so every absolute URL points at the same host
// (the apex, not www). Change this in one place if the domain ever moves.
export const SITE_URL = "https://aiengineerblog.com";

// Site-wide identity reused across metadata and structured data.
export const SITE_NAME = "AI Engineer Blog";
export const SITE_AUTHOR = "Nguyên";

// The strapline in the top strip above the header.
export const SITE_STRAPLINE = "Sổ tay kỹ thuật / AI Engineering Notebook";

// Cover images are generated by code (pipeline diagrams), so their frame is
// ours to choose. Set this to true once every cover in content/posts has been
// regenerated at a fixed 16/9 ratio on the --bg ground: full-bleed cover slots
// then switch from object-contain to object-cover and fill their frame edge to
// edge. Leave it false while any cover still has its own ratio, otherwise the
// old "thumbnail cut on both sides" bug comes back. See Thumbnail.tsx.
export const COVERS_FIXED_RATIO = true;
